{
 "title": "Mock-Server",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "status",
    "query": "label_values(requestTimer_ms_max, status)"
   },
   {
    "name": "method",
    "query": "label_values(requestTimer_ms_max, method)"
   },
   {
    "name": "path",
    "query": "label_values(requestTimer_ms_max, path)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview (ignores filters)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mock Server Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(requestTimer_ms_count[$__range])) by (path, status, method)"
    }
   ]
  },
  {
   "title": "Metrics Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(wiremock_metrics_errors_total[1m])) by (errType)",
     "legendFormat": "{{errType}}"
    }
   ]
  },
  { "title": "Relevant Dashboards", "type": "dashlist", "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 } },
  {
   "title": "Number of requests per status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_count{method=~\"$method\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Heap Usage %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"MockServer\", area=\"heap\"}) by (instance) *100 / sum(jvm_memory_max_bytes{application=\"MockServer\", area=\"heap\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Status $status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "status" },
  {
   "title": "Number Of Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "AVG Time per request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method) / sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}} |  {{path}}"
    }
   ]
  },
  { "title": "Status $status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Number Of Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "AVG Time per request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method) / sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}} |  {{path}}"
    }
   ]
  },
  { "title": "Status $status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Number Of Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "AVG Time per request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method) / sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}} |  {{path}}"
    }
   ]
  },
  { "title": "Status $status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Number Of Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "AVG Time per request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method) / sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}} |  {{path}}"
    }
   ]
  },
  { "title": "Status $status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Number Of Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "AVG Time per request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method) / sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}} |  {{path}}"
    }
   ]
  },
  { "title": "Status $status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Number Of Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}}:{{path}}"
    }
   ]
  },
  {
   "title": "AVG Time per request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requestTimer_ms_sum{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method) / sum(rate(requestTimer_ms_count{status=~\"$status\",method=~\"$method\", path=~\"$path\"}[1m])) by (path, status, method)",
     "legendFormat": "{{method}} |  {{path}}"
    }
   ]
  }
 ]
}